/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ixcd2
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        botonGeneral = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelGeneral = new javax.swing.JPanel();
        panelGeneral1 = new javax.swing.JPanel();
        panelGeneral2 = new javax.swing.JPanel();
        panelGeneral3 = new javax.swing.JPanel();
        panelGeneral4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 670));
        setResizable(false);
        setSize(new java.awt.Dimension(670, 670));

        jPanel1.setPreferredSize(new java.awt.Dimension(670, 670));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelMenu.setLayout(new java.awt.GridLayout());

        botonGeneral.setText("GENERAL");
        panelMenu.add(botonGeneral);

        jButton2.setText("jButton1");
        panelMenu.add(jButton2);

        jButton3.setText("jButton1");
        panelMenu.add(jButton3);

        jButton4.setText("jButton1");
        panelMenu.add(jButton4);

        jButton5.setText("jButton1");
        panelMenu.add(jButton5);

        jPanel1.add(panelMenu, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jPanel1.add(panelGeneral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelGeneral1Layout = new javax.swing.GroupLayout(panelGeneral1);
        panelGeneral1.setLayout(panelGeneral1Layout);
        panelGeneral1Layout.setHorizontalGroup(
            panelGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelGeneral1Layout.setVerticalGroup(
            panelGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jPanel1.add(panelGeneral1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelGeneral2Layout = new javax.swing.GroupLayout(panelGeneral2);
        panelGeneral2.setLayout(panelGeneral2Layout);
        panelGeneral2Layout.setHorizontalGroup(
            panelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelGeneral2Layout.setVerticalGroup(
            panelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jPanel1.add(panelGeneral2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelGeneral3Layout = new javax.swing.GroupLayout(panelGeneral3);
        panelGeneral3.setLayout(panelGeneral3Layout);
        panelGeneral3Layout.setHorizontalGroup(
            panelGeneral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelGeneral3Layout.setVerticalGroup(
            panelGeneral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jPanel1.add(panelGeneral3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelGeneral4Layout = new javax.swing.GroupLayout(panelGeneral4);
        panelGeneral4.setLayout(panelGeneral4Layout);
        panelGeneral4Layout.setHorizontalGroup(
            panelGeneral4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelGeneral4Layout.setVerticalGroup(
            panelGeneral4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jPanel1.add(panelGeneral4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGeneral;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelGeneral1;
    private javax.swing.JPanel panelGeneral2;
    private javax.swing.JPanel panelGeneral3;
    private javax.swing.JPanel panelGeneral4;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
