/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Santiagod
 */
public class PartidoPanel extends javax.swing.JPanel {
    
    private FrmGeneral frmGeneral;

    public PartidoPanel(FrmGeneral frmGeneral,ImageIcon imagenEquipo1, ImageIcon imagenEquipo2, String resultado, String estado, String fecha) {
        this.frmGeneral = frmGeneral;
        initComponents(imagenEquipo1, imagenEquipo2, resultado, estado, fecha);
    }

    private void initComponents(ImageIcon imagenEquipo1, ImageIcon imagenEquipo2, String resultado, String estado, String fecha) {
        setLayout(new BoxLayout(this, BoxLayout.X_AXIS));

        JLabel labelFecha = new JLabel(fecha);
        labelFecha.setFont(new Font("Arial", Font.PLAIN, 16));

        JButton btnAnterior = new JButton("< Anterior");
        btnAnterior.setFont(new Font("Arial", Font.PLAIN, 14));
        btnAnterior.addActionListener(e -> frmGeneral.mostrarPartidoAnterior());


        Box botoneraSuperior = Box.createHorizontalBox();
        botoneraSuperior.add(btnAnterior);
        botoneraSuperior.add(Box.createHorizontalStrut(10));
        botoneraSuperior.add(Box.createHorizontalGlue()); // Espacio horizontal flexible

        add(botoneraSuperior);

        JLabel labelImagen1 = new JLabel(imagenEquipo1);
        add(labelImagen1);
        add(Box.createRigidArea(new java.awt.Dimension(20, 10))); // Espacio vertical

        JLabel labelResultado = new JLabel(resultado);
        labelResultado.setFont(new Font("Arial", Font.BOLD, 18));
        add(labelResultado);
        add(Box.createRigidArea(new java.awt.Dimension(20, 5))); // Espacio vertical

        JLabel labelImagen2 = new JLabel(imagenEquipo2);
        add(labelImagen2);
        add(Box.createRigidArea(new java.awt.Dimension(20, 10))); // Espacio vertical

        JLabel labelEstado = new JLabel(estado);
        labelEstado.setFont(new Font("Arial", Font.PLAIN, 16));
        add(labelEstado);
        add(Box.createRigidArea(new java.awt.Dimension(20, 5))); // Espacio vertical

        add(labelFecha);
        add(Box.createRigidArea(new java.awt.Dimension(20, 20))); // Espacio vertical

//        JButton btnDetalles = new JButton("Detalles del Partido");
//        btnDetalles.setFont(new Font("Arial", Font.PLAIN, 14));
//        btnDetalles.addActionListener(e -> {
//            abrirInterfazEstadisticasPartido();
//        });
//
//        add(btnDetalles);

        add(labelFecha);
        add(Box.createRigidArea(new java.awt.Dimension(20, 20)));
        
        JButton btnSiguiente = new JButton("Siguiente >");
        btnSiguiente.setFont(new Font("Arial", Font.PLAIN, 14));
        btnSiguiente.addActionListener(e -> frmGeneral.mostrarPartidoSiguiente());


        Box botoneraInferior = Box.createHorizontalBox();
        botoneraInferior.add(Box.createHorizontalGlue()); // Espacio horizontal flexible
        botoneraInferior.add(btnSiguiente);

        add(botoneraInferior);
    
    }
    public PartidoPanel() {
        initComponents(null, null, "", "", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelImagen1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(634, 140));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        LabelImagen1.setText("holaa");
        LabelImagen1.setAlignmentX(2.0F);
        add(LabelImagen1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImagen1;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidoPanel().setVisible(true);
            }
        });
    }


}
